import {
  Coffee,
  Car,
  Shirt,
  Hamburger,
  Trees,
  Heart,
  Home,
  Book,
  DollarSign,
  Gift,
  TrendingUp,
  Star,
  MoreHorizontal,
  Airplay,
  Ban,
  ShoppingBag,
  Bike,
  Bone,
  FileText,
  Briefcase,
  Brush,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Video,
  Camera,
  Candy,
  ShoppingCart,
} from "lucide-react";

export const categoryIcons = [
  { name: "coffee", icon: Coffee },
  { name: "hamburger", icon: Hamburger },
  { name: "car", icon: Car },
  { name: "shirt", icon: Shirt },
  { name: "trees", icon: Trees },
  { name: "heart", icon: Heart },
  { name: "home", icon: Home },
  { name: "book", icon: Book },
  { name: "dollarSign", icon: DollarSign },
  { name: "gift", icon: Gift },
  { name: "trendingUp", icon: TrendingUp },
  { name: "star", icon: Star },
  { name: "moreHorizontal", icon: MoreHorizontal },
  { name: "airplay", icon: Airplay },
  { name: "ban", icon: Ban },
  { name: "shoppingBag", icon: ShoppingBag },
  { name: "bike", icon: Bike },
  { name: "bone", icon: Bone },
  { name: "fileText", icon: FileText },
  { name: "briefcase", icon: Briefcase },
  { name: "brush", icon: Brush },
  { name: "bus", icon: Bus },
  { name: "cake", icon: Cake },
  { name: "calculator", icon: Calculator },
  { name: "calendar", icon: Calendar },
  { name: "video", icon: Video },
  { name: "camera", icon: Camera },
  { name: "candy", icon: Candy },
  { name: "shoppingCart", icon: ShoppingCart },
];
